/*The MIT License (MIT)

 Copyright (c) 2016 MicheleBarcelos

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.*/
package model;
// Generated 05/12/2015 18:26:36 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda implements java.io.Serializable {

    private Integer codVenda;
    private Cliente cliente;
    private Formapagto formapagto;
    private Vendedor vendedor;
    private Date dataVenda;
    private BigDecimal valorVenda;
    private Integer desconto;
    private BigDecimal comissao;
    private Set items = new HashSet(0);

    public Venda() {
    }

    public Venda(Cliente cliente, Formapagto formapagto, Vendedor vendedor, Date dataVenda) {
        this.cliente = cliente;
        this.formapagto = formapagto;
        this.vendedor = vendedor;
        this.dataVenda = dataVenda;
    }

    public Venda(Cliente cliente, Formapagto formapagto, Vendedor vendedor, Date dataVenda, BigDecimal valorVenda, Integer desconto, BigDecimal comissao, Set items) {
        this.cliente = cliente;
        this.formapagto = formapagto;
        this.vendedor = vendedor;
        this.dataVenda = dataVenda;
        this.valorVenda = valorVenda;
        this.desconto = desconto;
        this.comissao = comissao;
        this.items = items;
    }

    public Integer getCodVenda() {
        return this.codVenda;
    }

    public void setCodVenda(Integer codVenda) {
        this.codVenda = codVenda;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Formapagto getFormapagto() {
        return this.formapagto;
    }

    public void setFormapagto(Formapagto formapagto) {
        this.formapagto = formapagto;
    }

    public Vendedor getVendedor() {
        return this.vendedor;
    }

    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }

    public Date getDataVenda() {
        return this.dataVenda;
    }

    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }

    public BigDecimal getValorVenda() {
        return this.valorVenda;
    }

    public void setValorVenda(BigDecimal valorVenda) {
        this.valorVenda = valorVenda;
    }

    public Integer getDesconto() {
        return this.desconto;
    }

    public void setDesconto(Integer desconto) {
        this.desconto = desconto;
    }

    public BigDecimal getComissao() {
        return this.comissao;
    }

    public void setComissao(BigDecimal comissao) {
        this.comissao = comissao;
    }

    public Set getItems() {
        return this.items;
    }

    public void setItems(Set items) {
        this.items = items;
    }

}
